export default function Page() {
  return <p>Have you ever had a moment where you were consumed by a sudden surge of inspiration or just a bout of motivation that had enticed you to pursue a desire that you had? Be it a lingering thought or an idea that decided today was the day it shall make its audition to be added to the vast aspirations you have accumulated from your wandering mind. But as you began to humour this thought, sitting down or going out to fulfil this now vulnerable craving, you hit something hard. The roadblock. The enforcer of your will, the lecturer of your hubris. It invalidates you so much that you begin to crawl back to your burrow, hoping you would never have these thoughts again. 

This is me being rather hyperbolic, but I am discussing the enemy of the inspired. Stuckness. Though I have just plastered on a suffix, I firmly believe that this portmanteau can fit as a placeholder for what I will be gabbing about. But to the ponderous, we often question why this happens. Of course, I am not about to shower you with sources, as I have not consumed much media, and the entire purpose of this site is to just go off on tangents and show someone's notes. I suppose I have inadvertently turned into a blogger... 

But let me get to the point: stuckness like this has many forms. Artist’s block is a well-known example, standing before a canvas and not having a single fruitful thought. Personally, I see artist’s block as another facet of burnout, because I find that whenever you coerce someone to stop drawing, the desire comes, not in full force mind you, but it comes to satiate. Creativity is a desire; it cannot be satisfied in bulk. You cannot scoff down the cheese board; you must mix and ’match and share the joy. That is the best resolve in that stuckness, to relax your mind, sit back and become the spectator to the world and regain that ire. 

We can even generalise this issue more, as not everyone is striving to begin the next great art movement. Because when we look wider, stuckness happens because of the absence of something, usually knowledge. I have a cringe-worthy memory as a child of me struggling with the Joker boss fight in Lego Batman 2, the one where Joker is on a boat. I was a snivelling mess all because I could not aim for shit and did not have the gamer know-how to understand when I could blast that stupid green-haired shit. 

It seems that we now excuse a lot of issues that we have that are primarily caused by a lack of knowledge, which thus causes our sense of stuckness. This then invalidates us, making us believe that our urges have no true purpose, as we are not capable of acting on this. I do recall that this is an issue amongst most activists, as they do agree in a cause, but only a third of those supporters would actively support their beliefs, and the rest are rather nihilistic about attaining the goal. Surrendering their goals because they believe there is no point in trying. 

I felt like making this essay, as I had made this site. To clarify, I am not some outstanding programmer; I am just rather tech-savvy and astonishingly stubborn. I just had a random spell of creativity and wanted an outlet for my ramblings. I surround myself with game developers, artists, musicians and what have you; I see this cycle again and again. Usually for such hobbies and careers, you require a suitable support system, but when you do not finish any projects, people do not believe you ever will and become drained from needing to support your endeavours or the aftermath of failure. Why should they support you when you do not meet your own goals, as then it gets perceived as leeching? But I did finish my project in the end, but I did put my bar excruciatingly low. </p>;
}